//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmadeusProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string TECHSTACK { get; set; }
        public string DESCRIPTION { get; set; }
        public string THUMBNAIL { get; set; }
        public string PICTURE1 { get; set; }
        public string PICTURE2 { get; set; }
        public string PICTURE3 { get; set; }
        public string PICTURE4 { get; set; }
        public string PICTURE5 { get; set; }
    }
}
